"""empty message

Revision ID: 6143634d8422
Revises: 89bd6e4a8e0c
Create Date: 2022-08-10 15:22:29.121759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6143634d8422'
down_revision = '89bd6e4a8e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('show', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('venue', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_at')
    op.drop_column('show', 'created_at')
    op.drop_column('artist', 'created_at')
    # ### end Alembic commands ###
