"""empty message

Revision ID: 617dea5f3bf6
Revises: 77c1b1f982db
Create Date: 2022-08-08 17:00:34.289627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617dea5f3bf6'
down_revision = '77c1b1f982db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
